language: python

matrix:
    include:
        - python: 2.7
          os: linux
          env: BUILD_COMMAND=sdist

        - python: 3.4
          os: linux
          env: BUILD_COMMAND=sdist

        - python: 3.5
          os: linux
          env: BUILD_COMMAND=sdist

        - language: generic
          os: osx
          env: BUILD_COMMAND=bdist_wheel

cache:
    apt: true

addons:
    apt:
        packages:
            - libhdf5-serial-1.8.4
            - libhdf5-serial-dev

install:
    # Mac OS X specific bootstrap
    - source ./ci/travis_osx.sh
    - travis_osx_install_begin

    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - pip install --upgrade pip

    # Install build dependencies
    - pip install wheel
    - pip install --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse/ numpy

    # Print Python info
    - python ./ci/info_platform.py
    - pip freeze

    # Generate source package or wheel
    - python setup.py $BUILD_COMMAND
    - ls dist

    # Mac OS X specific cleanup
    - travis_osx_install_end

script:
    # Mac OS X specific bootstrap
    - travis_osx_run_begin

    # Upgrade distribution modules
    - pip install --upgrade setuptools
    - pip install --upgrade pip

    # Install from source package
    - pip install --pre --find-links dist/ --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse/ xsocs

    # Print Python info
    - python ci/info_platform.py
    - pip freeze

    # Run the tests
    - python run_tests.py

    # Mac OS X specific cleanup
    - travis_osx_run_end
