os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'

# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"
        VENV_BUILD_DIR: "venv_build"
        VENV_TEST_DIR: "venv_test"

    matrix:
        # Python 3.5
        - PYTHON_DIR: "C:\\Python35-x64"
          QT_BINDINGS: "PyQt5"

        # Python 2.7
        - PYTHON_DIR: "C:\\Python27-x64"
          QT_BINDINGS: "PyQt4"

        - PYTHON_DIR: "C:\\Python27-x64"
          QT_BINDINGS: "PySide"

install:
    # Add Python to PATH
    - "SET PATH=%PYTHON_DIR%;%PYTHON_DIR%\\Scripts;%PATH%"

    # Upgrade distribution modules
    # Disabled as pip uprade fails
    # - "pip install --upgrade setuptools"
    # - "pip install --upgrade pip"

    # Install virtualenv
    - "pip install virtualenv"
    - "virtualenv --version"

build_script:
    # Create build virtualenv
    - "virtualenv --clear %VENV_BUILD_DIR%"
    - "%VENV_BUILD_DIR%\\Scripts\\activate.bat"

    # Install buils dependencies
    - "pip install wheel"
    - "pip install --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse/ numpy"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    # Build
    - "python setup.py bdist_wheel bdist_msi"
    - ps: "ls dist"

    # Leave build virtualenv
    - "%VENV_BUILD_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_BUILD_DIR% /s /q"

test_script:
    # Create test virtualenv
    - "virtualenv --clear %VENV_TEST_DIR%"
    - "%VENV_TEST_DIR%\\Scripts\\activate.bat"

    # Install Qt binding and matplotlib (until they are dependencies)
    # Install PyQt4 from www.edna-site.org and PyQt5/PySide from pypi
    - "pip install --pre --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse/ %QT_BINDINGS%"
    - "pip install matplotlib"

    # Install the generated wheel package to test it
    #- "pip install --pre --find-links dist/ --trusted-host www.edna-site.org --find-links http://www.edna-site.org/pub/wheelhouse/ xsocs"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"

    - "python run_tests.py"

    # Leave test virtualenv
    - "%VENV_TEST_DIR%\\Scripts\\deactivate.bat"
    - "rmdir %VENV_TEST_DIR% /s /q"

artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
